# Generated by Django 5.2.13 on 2026-04-24 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('envios', '0002_alter_encomienda_id'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='encomienda',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Encomienda', 'verbose_name_plural': 'Encomiendas'},
        ),
        migrations.RenameField(
            model_name='encomienda',
            old_name='fecha_envio',
            new_name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='encomienda',
            name='fecha_entrega',
        ),
        migrations.AddField(
            model_name='encomienda',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encomienda',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envios_como_destinatario', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='fecha_entrega_est',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='fecha_entrega_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='remitente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envios_como_remitente', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas', to='rutas.ruta'),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='volumen_cm3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En tránsito'), ('DE', 'En destino'), ('EN', 'Entregado'), ('DV', 'Devuelto')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='encomienda',
            table='encomiendas',
        ),
        migrations.AddField(
            model_name='encomienda',
            name='empleado_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas_registradas', to='envios.empleado'),
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=2)),
                ('estado_nuevo', models.CharField(max_length=2)),
                ('observacion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envios.empleado')),
                ('encomienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='envios.encomienda')),
            ],
        ),
    ]
