# Generated by Django 5.2.13 on 2026-05-15 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0004_alter_empleado_id_alter_encomienda_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='historialestado',
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historiales de Estados'},
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='empleados',
        ),
        migrations.AlterModelTable(
            name='historialestado',
            table='historial_estados',
        ),
    ]
